name: Deploy to AWS Lambda

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write   # This is required for OIDC authentication
  contents: read    # This is required to checkout the repository

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-2
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ env.AWS_REGION }}
        # The role-to-assume should be the ARN of the IAM role you created for GitHub Actions OIDC
  
    - name: Clean app folder
      run: |
        find app -type d -name "__pycache__" -exec rm -rf {} +
        
    - name: Prepare deployment package
      run: |
        rm -rf deploy_package deploy.zip || true
        mkdir deploy_package
        cp -r app deploy_package/
        
    - name: Deploy Lambda Function
      uses: aws-actions/aws-lambda-deploy@v1.1.0
      with:
        function-name: stint-tracker-api
        code-artifacts-dir: ./deploy_package
        handler: main.handler
        runtime: python3.13
        # Add any additional inputs this action supports
        
    - name: Clean up deployment package
      run: |
        rm -rf deploy_package
